apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log
  template:
    metadata:
      labels:
        app: log
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: log-writter
          image: ebrhoden/log-writter:0.0.1
          volumeMounts:
            - name: shared-data
              mountPath: /shared
        - name: log-reader
          image: ebrhoden/log-reader:0.0.1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: shared-data
              mountPath: /shared