apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-dep
  namespace: project
spec:
  replicas: 1

  selector:
    matchLabels:
      app: todoapp

  template:
    metadata:
      labels:
        app: todoapp

    spec:
      containers:
        - name: todoapp
          image: ebrhoden/todo_app:0.0.6

          envFrom:
            - configMapRef:
                name: todoapp-config

          volumeMounts:
            - name: image-storage
              mountPath: /data

      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: todoapp-pvc
